=== AlexeyEvlampiev/Nature/src/Nature/ChemicalElementInfo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="elements">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="element">
          <xs:complexType>
            <xs:attribute name="Code" type="xs:string" use="required" />
            <xs:attribute name="Name" type="xs:string" use="required" />
            <xs:attribute name="Mass" type="xs:double" use="required" />
            <xs:attribute name="Valency" type="xs:unsignedByte" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AlexeyEvlampiev/Nature/src/Nature/ChemicalElementInfo.xml
<elements xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ChemicalElementInfo.xsd">
  <element Code="AC" Name="Actinium" Mass="2.270000000000000e-001" Valency="89" />
  <element Code="AG" Name="Silver" Mass="1.078682000000000e-001" Valency="47" />
  <element Code="AL" Name="Aluminum" Mass="2.698154000000000e-002" Valency="13" />
  <element Code="AM" Name="Americium" Mass="2.430000000000000e-001" Valency="95" />
  <element Code="AR" Name="Argon" Mass="3.994800000000000e-002" Valency="18" />
  <element Code="AS" Name="Arsenic" Mass="7.492159000000000e-002" Valency="33" />
  <element Code="AT" Name="Astatine" Mass="2.100000000000000e-001" Valency="85" />
  <element Code="AU" Name="Gold" Mass="1.969665000000000e-001" Valency="79" />
  <element Code="B" Name="Boron" Mass="1.081100000000000e-002" Valency="5" />
  <element Code="BA" Name="Barium" Mass="1.373270000000000e-001" Valency="56" />
  <element Code="BE" Name="Beryllium" Mass="9.012181999999999e-003" Valency="4" />
  <element Code="BI" Name="Bismuth" Mass="2.089804000000000e-001" Valency="83" />
  <element Code="BK" Name="Berkelium" Mass="2.470000000000000e-001" Valency="97" />
  <element Code="BR" Name="Bromine" Mass="7.990400000000000e-002" Valency="35" />
  <element Code="C" Name="Carbon" Mass="1.201100000000000e-002" Valency="6" />
  <element Code="CA" Name="Calcium" Mass="4.007800000000000e-002" Valency="20" />
  <element Code="CD" Name="Cadmium" Mass="1.124110000000000e-001" Valency="48" />
  <element Code="CE" Name="Cerium" Mass="1.401150000000000e-001" Valency="58" />
  <element Code="CF" Name="Californium" Mass="2.470000000000000e-001" Valency="98" />
  <element Code="CL" Name="Chlorine" Mass="3.545270000000000e-002" Valency="17" />
  <element Code="CM" Name="Curium" Mass="2.470000000000000e-001" Valency="96" />
  <element Code="CO" Name="Cobalt" Mass="5.893320000000000e-002" Valency="27" />
  <element Code="CR" Name="Chromium" Mass="5.199610000000000e-002" Valency="24" />
  <element Code="CS" Name="Cesium" Mass="1.329054000000000e-001" Valency="55" />
  <element Code="CU" Name="Copper" Mass="6.354600000000001e-002" Valency="29" />
  <element Code="D" Name="Deuterium" Mass="2.014101778000000e-003" Valency="5" />
  <element Code="DY" Name="Dysprosium" Mass="1.625000000000000e-001" Valency="66" />
  <element Code="ER" Name="Erbium" Mass="1.672600000000000e-001" Valency="68" />
  <element Code="ES" Name="Einsteinium" Mass="2.510000000000000e-001" Valency="99" />
  <element Code="EU" Name="Europium" Mass="1.519650000000000e-001" Valency="63" />
  <element Code="F" Name="Fluorine" Mass="1.899840000000000e-002" Valency="9" />
  <element Code="FE" Name="Iron" Mass="5.584700000000000e-002" Valency="26" />
  <element Code="FM" Name="Fermium" Mass="2.570000000000000e-001" Valency="100" />
  <element Code="FR" Name="Francium" Mass="2.230000000000000e-001" Valency="87" />
  <element Code="GA" Name="Gallium" Mass="6.972300000000001e-002" Valency="31" />
  <element Code="GD" Name="Gadolinium" Mass="1.572500000000000e-001" Valency="64" />
  <element Code="GE" Name="Germanium" Mass="7.261000000000001e-002" Valency="32" />
  <element Code="H" Name="Hydrogen" Mass="1.007940000000000e-003" Valency="1" />
  <element Code="HE" Name="Helium" Mass="4.002602000000001e-003" Valency="2" />
  <element Code="HF" Name="Hafnium" Mass="1.784900000000000e-001" Valency="72" />
  <element Code="HG" Name="Mercury" Mass="2.005900000000000e-001" Valency="80" />
  <element Code="HO" Name="Holmium" Mass="1.649303000000000e-001" Valency="67" />
  <element Code="I" Name="Iodine" Mass="1.269044700000000e-001" Valency="53" />
  <element Code="IN" Name="Indium" Mass="1.148200000000000e-001" Valency="49" />
  <element Code="IR" Name="Iridium" Mass="1.922200000000000e-001" Valency="77" />
  <element Code="K" Name="Potassium" Mass="3.909830000000000e-002" Valency="19" />
  <element Code="KR" Name="Krypton" Mass="8.380000000000000e-002" Valency="36" />
  <element Code="LA" Name="Lanthanum" Mass="1.389055000000000e-001" Valency="57" />
  <element Code="LI" Name="Lithium" Mass="6.941000000000000e-003" Valency="3" />
  <element Code="LU" Name="Lutetium" Mass="1.749670000000000e-001" Valency="71" />
  <element Code="MG" Name="Magnesium" Mass="2.430500000000000e-002" Valency="12" />
  <element Code="MN" Name="Manganese" Mass="5.493805000000000e-002" Valency="25" />
  <element Code="MO" Name="Molybdenum" Mass="9.594000000000000e-002" Valency="42" />
  <element Code="N" Name="Nitrogen" Mass="1.400674000000000e-002" Valency="7" />
  <element Code="NA" Name="Sodium" Mass="2.298977000000000e-002" Valency="11" />
  <element Code="NB" Name="Niobium" Mass="9.290638000000000e-002" Valency="41" />
  <element Code="ND" Name="Neodymium" Mass="1.442400000000000e-001" Valency="60" />
  <element Code="NE" Name="Neon" Mass="2.017970000000000e-002" Valency="10" />
  <element Code="NI" Name="Nickel" Mass="5.869340000000000e-002" Valency="28" />
  <element Code="NP" Name="Neptunium" Mass="2.370482000000000e-001" Valency="93" />
  <element Code="O" Name="Oxygen" Mass="1.599940000000000e-002" Valency="8" />
  <element Code="OS" Name="Osmium" Mass="1.902000000000000e-001" Valency="76" />
  <element Code="P" Name="Phosphorus" Mass="3.097376000000000e-002" Valency="15" />
  <element Code="PA" Name="Protactinium" Mass="2.310358800000000e-001" Valency="91" />
  <element Code="PB" Name="Lead" Mass="2.072000000000000e-001" Valency="82" />
  <element Code="PD" Name="Palladium" Mass="1.064200000000000e-001" Valency="46" />
  <element Code="PM" Name="Promethium" Mass="1.450000000000000e-001" Valency="61" />
  <element Code="PO" Name="Polonium" Mass="2.090000000000000e-001" Valency="84" />
  <element Code="PR" Name="Praseodymium" Mass="1.409077000000000e-001" Valency="59" />
  <element Code="PT" Name="Platinum" Mass="1.950800000000000e-001" Valency="78" />
  <element Code="PU" Name="Plutonium" Mass="2.440000000000000e-001" Valency="94" />
  <element Code="RA" Name="Radium" Mass="2.260254000000000e-001" Valency="88" />
  <element Code="RB" Name="Rubidium" Mass="8.546780000000000e-002" Valency="37" />
  <element Code="RE" Name="Rhenium" Mass="1.862070000000000e-001" Valency="75" />
  <element Code="RH" Name="Rhodium" Mass="1.029055000000000e-001" Valency="45" />
  <element Code="RN" Name="Radon" Mass="2.220000000000000e-001" Valency="86" />
  <element Code="RU" Name="Ruthenium" Mass="1.010700000000000e-001" Valency="44" />
  <element Code="S" Name="Sulfur" Mass="3.206600000000000e-002" Valency="16" />
  <element Code="SB" Name="Antimony" Mass="1.217570000000000e-001" Valency="51" />
  <element Code="SC" Name="Scandium" Mass="4.495591000000000e-002" Valency="21" />
  <element Code="SE" Name="Selenium" Mass="7.895999999999999e-002" Valency="34" />
  <element Code="SI" Name="Silicon" Mass="2.808550000000000e-002" Valency="14" />
  <element Code="SM" Name="Samarium" Mass="1.503600000000000e-001" Valency="62" />
  <element Code="SN" Name="Tin" Mass="1.187100000000000e-001" Valency="50" />
  <element Code="SR" Name="Strontium" Mass="8.762000000000000e-002" Valency="38" />
  <element Code="TA" Name="Tantalum" Mass="1.809479000000000e-001" Valency="73" />
  <element Code="TB" Name="Terbium" Mass="1.589253000000000e-001" Valency="65" />
  <element Code="TC" Name="Technetium" Mass="9.800000000000000e-002" Valency="43" />
  <element Code="TE" Name="Tellurium" Mass="1.276000000000000e-001" Valency="52" />
  <element Code="TH" Name="Thorium" Mass="2.320381000000000e-001" Valency="90" />
  <element Code="TI" Name="Titanium" Mass="4.788000000000001e-002" Valency="22" />
  <element Code="TL" Name="Thallium" Mass="2.043833000000000e-001" Valency="81" />
  <element Code="TM" Name="Thulium" Mass="1.689342000000000e-001" Valency="69" />
  <element Code="U" Name="Uranium" Mass="2.380289000000000e-001" Valency="92" />
  <element Code="V" Name="Vanadium" Mass="5.094150000000000e-002" Valency="23" />
  <element Code="W" Name="Tungsten" Mass="1.838500000000000e-001" Valency="74" />
  <element Code="XE" Name="Xenon" Mass="1.312900000000000e-001" Valency="54" />
  <element Code="Y" Name="Yttrium" Mass="8.890585000000001e-002" Valency="39" />
  <element Code="YB" Name="Ytterbium" Mass="1.730400000000000e-001" Valency="70" />
  <element Code="ZN" Name="Zinc" Mass="6.539000000000000e-002" Valency="30" />
  <element Code="ZR" Name="Zirconium" Mass="9.122400000000000e-002" Valency="40" />
</elements>
