=== AlexeyEvlampiev/Nature/src/Nature/Constants.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Constants">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="Add">
          <xs:complexType>
            <xs:attribute name="Code" type="xs:string" use="required" />
            <xs:attribute name="Value" type="xs:string" use="required" />
            <xs:attribute name="Units" type="xs:string" use="required" />
            <xs:attribute name="ClrType" type="xs:string" use="required" />
            <xs:attribute name="Quantity" type="xs:string" use="required" />
            <xs:attribute name="Description" type="xs:string" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== AlexeyEvlampiev/Nature/src/Nature/Constants.xml
<Constants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Constants.xsd">
  <Add Code="Angstrom" Value="1.0e-10" Units="m" ClrType="double" Quantity="Angstrom" Description="The angstrom or ångström  is a unit of length equal to 1/10,000,000,000 (one ten billionth) of a meter (1×10-10 m or 100 pm). Its symbol is the Swedish letter Å." />
  <Add Code="Atmosphere" Value="101325.0" Units="Pa" ClrType="double" Quantity="Standard atmosphere" Description="The standard atmosphere (symbol: atm) is an international reference pressure defined as 101.325 kPa and formerly used as unit of pressure. For practical purposes it has been replaced by the bar which is 105 Pa. The difference of about 1% is not significant for many applications, and is within the error range of common pressure gauges." />
  <Add Code="AtomicMassUnit" Value="1.660538921e-27" Units="kg" ClrType="double" Quantity="Atomic mass unit (unified atomic mass unit)" Description="The unified atomic mass unit (also known as amu, symbol: u) or dalton (symbol: Da) is the standard unit that is used for indicating mass on an atomic or molecular scale (atomic mass). It is defined as one twelfth of the rest mass of an unbound neutral atom of carbon-12 in its nuclear and electronic ground state, and has a value of 1.660538921(73)×10-27 kg. One dalton is approximately equal to the mass of one proton or one neutron. The CIPM have categorised it as a &quot;non-SI unit&quot; because units values in SI units must be obtained experimentally." />
  <Add Code="Avogadro" Value="6.02214129e+23" Units="1/mol" ClrType="double" Quantity="Avogadro's number" Description="In chemistry and physics, the Avogadro constant (symbols: L, NA) is defined as the ratio of the number of constituent particles N (usually atoms or molecules) in a sample to the amount of substance n (unit mole) through the relationship NA = N/n. Thus, it is the proportionality factor that relates the molar mass of an entity, i.e., the mass per amount of substance, to the mass of said entity. The Avogadro constant expresses the number of elementary entities per mole of substance and it has the value 6.02214129(27)×1023 mol-1. Changes in the SI units are proposed that will change Avogadro's constant to exactly 6.02214X×1023 when it is expressed in the unit mol-1 (see New SI definitions)." />
  <Add Code="BohrMagneton" Value="9.27400968e-24" Units="J/T" ClrType="double" Quantity="Bohr magneton" Description="In atomic physics, the Bohr magneton (symbol µB) is a physical constant and the natural unit for expressing an electron magnetic dipole moment" />
  <Add Code="BohrRadius" Value="5.2917721092e-11" Units="m" ClrType="double" Quantity="Bohr radius" Description="The Bohr radius is a physical constant, approximately equal to the most probable distance between the proton and electron in a hydrogen atom in its ground state. It is named after Niels Bohr, due to its role in the Bohr model of an atom." />
  <Add Code="Boltzmann" Value="1.3806488e-23" Units="J/K" ClrType="double" Quantity="Boltzmann constant" Description="The Boltzmann constant (k or kB) is the physical constant relating energy at the individual particle level with temperature, which must necessarily be observed at the collective or bulk level" />
  <Add Code="CharacteristicImpedanceOfVacuum" Value="376.730313461" Units="V/A" ClrType="double" Quantity="Characteristic impedance of vacuum" Description="The impedance of free space, Z0, is a physical constant relating the magnitudes of the electric and magnetic fields of electromagnetic radiation travelling through free space. That is, Z0 = |E|/|H|, where |E| is the electric field strength and |H| magnetic field strength. It has an exact value, given approximately as 376.73031... ohms." />
  <Add Code="ClassicalElectronRadius" Value="2.8179403267e-15" Units="m" ClrType="double" Quantity="Classical electron radius" Description="The classical electron radius, also known as the Lorentz radius or the Thomson scattering length, is based on a classical (i.e., non-quantum) relativistic model of the electron." />
  <Add Code="ConductanceQuantum" Value="7.7480917346e-5" Units="S" ClrType="double" Quantity="Conductance quantum" Description="The conductance quantum (G0) is the quantized unit of electrical conductance. It appears when measuring the conductance of a quantum point contact, and, more generally, is a key component of Landauer formula which relates the electrical conductance of a quantum conductor to its quantum properties." />
  <Add Code="ConventionalValueOfJosephsonConstant" Value="4.835979e14" Units="Hz/V" ClrType="double" Quantity="Conventional value of Josephson constant" Description="The magnetic flux quantum F0 is the quantum of magnetic flux passing through a superconductor. The phenomenon of flux quantization was discovered by B. S. Deaver and W. M. Fairbank and, independently, by R. Doll and M. Nabauer, in 1961. The quantization of magnetic flux is closely related to the Little–Parks effect, but was predicted earlier by Fritz London in 1948 using a phenomenological model." />
  <Add Code="ConventionalValueOfVonKlitzingConstant" Value="25812.807" Units="V/A" ClrType="double" Quantity="Conventional value of von Klitzing constant" Description="The quantum Hall effect (or integer quantum Hall effect) is a quantum-mechanical version of the Hall effect, observed in two-dimensional electron systems subjected to low temperatures and strong magnetic fields, in which the Hall conductivity s takes on the quantized values" />
  <Add Code="Coulomb" Value="8.987551787e+9" Units="N*m^2/C^2" ClrType="double" Quantity="Coulomb's constant" Description="Coulomb's law states that: &quot;The magnitude of the Electrostatics force of interaction between two point charges is directly proportional to the scalar multiplication of the magnitudes of charges and inversely proportional to the square of the distances between them.&quot;" />
  <Add Code="Debye" Value="3.162e-25" Units="(J*m^3)^(1/2)" ClrType="double" Quantity="Debye" Description="The debye (symbol: D) is a CGS unit (a non-SI metric unit) of electric dipole moment named in honour of the physicist Peter J. W. Debye. It is defined as 1×10-18 statcoulomb-centimetre. Historically the debye was defined as the dipole moment resulting from two charges of opposite sign but an equal magnitude of 10-10 statcoulomb (generally called e.s.u. (electrostatic unit) in older literature), which were separated by 1 ångström." />
  <Add Code="ElectricConstant" Value="8.854187817e-12" Units="F/m" ClrType="double" Quantity="Electric constant (vacuum permittivity)" Description="The physical constant e0, commonly called the vacuum permittivity, permittivity of free space or electric constant is an ideal, (baseline) physical constant, which is the value of the absolute (not relative) dielectric permittivity of classical vacuum" />
  <Add Code="ElectronMass" Value="9.10938291e-31" Units="kg" ClrType="double" Quantity="Electron mass" Description="The electron (symbol: e-) is a subatomic particle with a negative elementary electric charge" />
  <Add Code="ElementaryCharge" Value="1.602176565e-19" Units="C" ClrType="double" Quantity="Elementary charge" Description="The elementary charge, usually denoted as e, is the electric charge carried by a single proton, or equivalently, the negation (opposite) of the electric charge carried by a single electron. This elementary charge is a fundamental physical constant. To avoid confusion over its sign, e is sometimes called the elementary positive charge. This charge has a measured value of approximately 1.602176565(35)×10-19 coulombs. In the cgs system, e is 4.80320425(10)×10-10 statcoulombs" />
  <Add Code="Faraday" Value="96485.3365" Units="C/mol" ClrType="double" Quantity="Faraday constant" Description="In physics and chemistry, the Faraday constant (named after Michael Faraday) is the magnitude of electric charge per mole of electrons. It has the currently accepted value F = 96,485.3365(21) C/mol" />
  <Add Code="FermiCouplingConstant" Value="1.166364e-5" Units="Ge/V^2" ClrType="double" Quantity="Fermi coupling constant" Description="In particle physics, Fermi's interaction is an explanation of the beta decay, proposed by Enrico Fermi, in which four fermions directly interact with one another at one vertex. For example, this interaction explains beta decay of a neutron by direct coupling of a neutron with an electron, antineutrino and a proton" />
  <Add Code="FineStructureConstant" Value="7.2973525698e-3" Units="~" ClrType="double" Quantity="Fine-structure constant" Description="In physics, the fine-structure constant (usually denoted a, the Greek letter alpha) is a fundamental physical constant, namely the coupling constant characterizing the strength of the electromagnetic interaction. Being a dimensionless quantity, it has constant numerical value in all systems of units. Arnold Sommerfeld introduced the fine-structure constant in 1916" />
  <Add Code="FirstRadiationConstant" Value="3.74177153e-16" Units="W*m^2" ClrType="double" Quantity="First radiation constant" Description="A constant appearing in the Planck radiation formula; its value depends on the form of the formula used; in the formula for power emitted by a blackbody per unit area per unit wavelength interval, it is 2p times Planck's constant, times the square of the speed of light, or approximately 3.74177 × 10-16 watt (meter)2. Symbolized c1; C1. " />
